name: Build docker image

on:
  push:
    tags:
      - 't*.*.*'
      - 'v*.*.*'
      - 'p*.*.*'
env:
  IMAGE_REPO_PROJECT: meta-task
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  CI:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.outputs.image_tag }}
    steps:
      - name: Configure AWS credentials
        id: aws_credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::234017874740:role/github-actions
#          role-to-assume: arn:aws:iam::129862287110:role/github-actions
          aws-region: us-east-2
          mask-aws-account-id: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: tag
        shell: bash
        run: |
          echo "image_tag=$GITHUB_REF_NAME" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_REPO_PROJECT }}:${{ steps.tag.outputs.image_tag }}
